Update Content Parser for ansible-lint 6.20.0
ansible/ansible-content-parser pull request #14
Opened 2023-09-20 16:24 UTC by TamiTakamiya

As ansible-lint 6.20.0 replace the `--write` option with the `--fix` option, I updated the Content Parser code accordingly.

Also I implemented the `--version` option to display the version of the Content Parser with the versions of `ansible-lint` and `ansible-core`.  The output would be like:
```
$ ansible-content-parser --version
ansible-content-parser 0.0.1 using ansible-lint:6.20.0 ansible-core:2.15.4
```

2023-09-25 19:09 UTC, robinbobbitt requested changes
Looking great! Two tiny comments and a question. I'm still messing with getting the unit tests to work successfully for me locally.

2023-09-25 19:41 UTC, TamiTakamiya commented on README.md
> +updates Ansible files (the `--fix option of `ansible-lint`)
Thanks!

2023-09-25 20:06 UTC, TamiTakamiya commented on src/ansible_content_parser/__main__.py
> +                if result["ruleId"].startswith("syntax-check"):
May I address this with [AAP-16412](https://issues.redhat.com/browse/AAP-16412)?

Current code runs `ansible-lint` primarily for utilizing its "transform" feature, which automatically fixes issues without human intervention.  I am not certain that the sage pipeline would work properly with excluding any file that had a violation.  I think we can provide an option to let user select the behavior from

1. Exclude files with syntax check errors only from sage pipeline (default)
2. Exclude any files with one or more violations from sage pipeline
3. Do not exclude any files

2023-09-25 20:06 UTC, TamiTakamiya commented on README.md
> +        - **Note:** If `ansible-content-parser` is executed with the `--no-exclude` option, the second execution
Yes, I will. Thanks!

2023-09-25 20:26 UTC, TamiTakamiya commented
@robinbobbitt I have addressed two README issues. 

On local builds, I tried following commands and got a successful result on my Fedora laptop:
```
mkdir /var/tmp/work
cd /var/tmp/work
python3 -m venv ./venv
source ./venv/bin/activate
git clone git@github.com:ansible/ansible-content-parser.git
cd ansible-content-parser
git switch ttakamiy/AAP-16281/lint-fix-option
tox
```
Would you try this sequence? Thanks!

Note: There was an error (actually two same messages) from scmtools_scm
```
ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
```
but they did not fail the build.  Since scmtools_scm is used for releasing, I think that would be OK.

2023-09-26 03:22 UTC, robinbobbitt commented on src/ansible_content_parser/__main__.py
> +                if result["ruleId"].startswith("syntax-check"):
We can definitely address in a follow-up. My thinking is that if they run with `--profile=safety`,e.g., ansible-lint run will fail on any file that violates that profile, and they're stuck unless they exclude those files, just as they're stuck if they don't exclude the syntax-check ones when no profile is specified. I'm not clear on why sage pipeline would have an issue... It would just be running over fewer files, right?

2023-09-26 03:23 UTC, robinbobbitt commented
> Would you try this sequence?

Success! And now it works in my original clone too. Thanks.

2023-09-26 03:23 UTC, robinbobbitt approved these changes

2023-09-26 03:44 UTC, merged