README update
ansible/ansible-content-parser pull request #21
Opened 2023-10-04 16:35 UTC by TamiTakamiya

1. Replace 
>  the `ftdata.json` file, which is the training dataset for developing custom AI models used with Ansible Lightspeed.

with

> the `ftdata.json` file, which is the training dataset for developing custom AI models.
following the suggestion from Marty.

2. Insert the installation steps from User Guide draft. Because this README will be viewable on GitHub and PyPI, readers are mostly engineers and they should be familiar with how pip works and these steps look too redundant.  **However, I still want to insert them to README here** because it would be pretty likely many of them already have Ansible libraries on their system and I would like them to install `ansible-content-parser` in an isolated virtual environment.

2023-10-05 20:39 UTC, robinbobbitt commented on README.md
> +  ` **Note:** Installation on Microsoft Windows OS is not supported.
stray backtick here

2023-10-05 20:43 UTC, robinbobbitt commented on README.md
> +$ python -m venv ./venv
Shall we take out the $s? They make a copy-paste unusable.

2023-10-05 20:48 UTC, robinbobbitt requested changes
These are fantastic directions and worked well for me! Just a couple minor adjustments suggested.

2023-10-05 21:22 UTC, TamiTakamiya commented on README.md
> +  ` **Note:** Installation on Microsoft Windows OS is not supported.
Thanks. Fixed it.

2023-10-05 21:29 UTC, TamiTakamiya commented on README.md
> +$ python -m venv ./venv
Removed '$'s.  I kept '$'s in the execution examples (outputs shown with the `--version` and `--help` options.)

2023-10-05 21:30 UTC, TamiTakamiya commented
@robinbobbitt Thanks for your comments. I have addressed your comments in the latest commit. Would you take a look? Thank you.

2023-10-06 02:19 UTC, robinbobbitt approved these changes
Thanks @TamiTakamiya !

2023-10-06 02:19 UTC, merged